### ISSUE TITLE
Enable compression?

### ISSUE THREAD

**Issue by EzequielAdrianM** [dragon66/android-gif-animated-writer#1]
Hi, I am working with bitmaps which are 720x840 and their size is normally 256KB.
When writing to Internal Storage, I compress them with Bitmap.compress() at 80 compression level.
The images doesn't loose too much quality and the size is incredibly reduced: 65KB.

I've used your GifWriter, but the final size of 6 frames is 1.5MB... What can I do to reduce the gif size?

**Comment by dragon66** [comment]
@EzequielAdrianM To reduce file size of an animated GIF, you can try several ways:
1. Do not use dither (you can set it to false when you create a new animated GIF writer)
2. Use only one global color map instead of one local color map for each frame (This is not available)
3. Use less colors when creating GIF image. Inside writeFrame() method, there is a variable called bitsPerPixel which is hard-coded as 8 which amounts to 256 colors for GIF. If you want to reduce the file size, you can reduce this value to anything between 8 and 2 (inclusive). The quality will be degraded though. You can add one more parameter to the method or the constructor for this purpose.

Hope that helps.

**Comment by EzequielAdrianM** [comment]
By setting Dither usage to false, the GIF size was reduced from 1.5MB to 1.2MB
And finally, by setting bitsPerPixel to 7, the size was reduced again from 1.2MB to 970KB.
Still conserving most of the original Quality...

I did not understand the second step you have mentioned, It will be great if you can give me further explanations. Otherwise, I've reached the scope of reducing size. Thanks!

**Comment by dragon66** [comment]
@EzequielAdrianM   I believe you know that GIF is one kind of indexed color images which save the indexes of colors and use them to map to actual colors in the color map. For an animated GIF, there are usually two ways to serve the color map. 1. use a global color map which maximum 256 colors. Each frame of the animated GIF will use the one and only global map. 2. Use or don't use a global color map, instead, provide a local color map for each frame. The second approach is more flexible. For example, the first frame contains 128 color and the second frame contains 256 color or it may contain the same number of colors but the colors may be completely different for the two frames. In this case, you won't be able to use only one global color map as it provides the same colors.

Since we use one color map for each frame, the size of the animated GIF will increase especially if the animated GIF contains a lot of frames.

**Comment by EzequielAdrianM** [comment]
And, I guess your GifWriter uses Local color map for each frame?

**Comment by dragon66** [comment]
Yes except the first frame which uses the global one. 

I tried to optimize a small animated GIF to use only one global color map which is documented here: https://github.com/dragon66/icafe/issues/3 and you can find details about it on the Wiki page. The gain may not be so significant compared to the effort and the whole file size as each color map consumes at most 768 bytes. 

The other two choices are the ones you should focus on.

**Comment by EzequielAdrianM** [comment]
Ok, I see, so @dragon66 Thanks for your help!
